available_text_models: ["gpt-4o-mini","gpt-4o"]

info:
  gpt-4o-mini:
    type: chat_completion
    name: GPT-4o Mini
    description: GPT-4o Mini is a lighter version of GPT-4o, offering <b>faster</b> performance. It is suitable for moderately complex tasks.

    price_per_1000_input_tokens: 0.008
    price_per_1000_output_tokens: 0.015

    scores:
      smart: 4
      fast: 5
      cheap: 4

  gpt-4o:
    type: chat_completion
    name: GPT-4o
    description: GPT-4o is the main choice for <b>intelligent</b> tasks.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.02

    scores:
      smart: 4
      fast: 4
      cheap: 3

  dalle-2:
    type: image
    price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006
